### ISSUE TITLE
request vulnerability

### ISSUE THREAD

**Issue by isatria** [loopbackio/strong-soap#335]
Vulnerability: [SRCCLR-SID-3911](https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-3911/summary) & [SRCCLR-SID-21913](https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-21913/summary) Medium severity.
Dependency: *request*

Are you have the schedule to resolve this issue anytime soon?

It's causing a medium severity vulnerability and that package deprecated already too.

**Comment by achrinza** [comment]
Thanks for initiating a discussion @isatria.

Based on what I can find on these vulnerabilities, the first vulnerability only affects oauth signing, which is not being used by this package, while the 2nd vulnerability is with regards to a configuration option, which isn't directly utilised by this package. (Feel free to correct me on those).

Regardless of the above, we do plan to eventually migrate away from Request. Though there isn't anyone actively working on it at the moment due to resource constraints with maintaining the other NPM packages.

I'll proceed to close this issue in favour of https://github.com/loopbackio/strong-soap/issues/328 so that we can consolidate the discussion.

**Comment by achrinza** [comment]
Duplicate of #328
